/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/home`; params?: Router.UnknownInputParams; } | { pathname: `/../components/screens/homePage/headerHome`; params?: Router.UnknownInputParams; } | { pathname: `/../components/screens/homePage/body`; params?: Router.UnknownInputParams; } | { pathname: `/../components/organisms/ButtonLink`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/linkHome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/service`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/home`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/screens/homePage/headerHome`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/screens/homePage/body`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/organisms/ButtonLink`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/linkHome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Drawer/service`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Drawer/home${`?${string}` | `#${string}` | ''}` | `/../components/screens/homePage/headerHome${`?${string}` | `#${string}` | ''}` | `/../components/screens/homePage/body${`?${string}` | `#${string}` | ''}` | `/../components/organisms/ButtonLink${`?${string}` | `#${string}` | ''}` | `/../hooks/linkHome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Drawer/service${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/home`; params?: Router.UnknownInputParams; } | { pathname: `/../components/screens/homePage/headerHome`; params?: Router.UnknownInputParams; } | { pathname: `/../components/screens/homePage/body`; params?: Router.UnknownInputParams; } | { pathname: `/../components/organisms/ButtonLink`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/linkHome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Drawer/service`; params?: Router.UnknownInputParams; };
    }
  }
}
